language: python
python:
- '3.7'
branches:
  only: master
install:
- pip install awscli
- pip install aws-sam-cli
script:
- sam validate
- sam build -b build/
- sam package --template-file build/template.yaml --s3-bucket $BUILD_ARTIFACT_BUCKET --output-template-file build/packaged.yaml
deploy:
  provider: script
  script: bash deploy.sh
  skip_cleanup: true
  on:
    branch: master
notifications:
  email: false
env:
  global:
  - BUILD_ARTIFACT_BUCKET=kaustubhk-build-artifacts
  - AWS_DEFAULT_REGION=us-east-1
  - AWS_DEFAULT_OUTPUT=json
  - secure: xz7nf+hqZF8EuN4AayJTeFHM9xZ0FJSNWHtjPVO5vXs+x6hJJnKjPn8SlBlEcLwYf6O7jj4UXE5rmXpNPKo28GX4DcmWlnIipINkZ5a2YlDFmBSVi6tczOiE4pPYEa/zzXKFHjPAbKtNxkKSLoYNBe05/oV171IRZqHqK6vqo3I03PLqFE319denkCMX0abxvrqwQW80ftFOgIvyUektkZ10GcHvPg70lqEW+Cr219pn8WY0uo3rNVsT8g/FmP2vGFFcLDJH/RTOgs43wxSydRM9MUk8fptUEBgJWKhV1NQ7+WnlvrgE/fJ9Sv2TnVVKe78ENg+oygZSqiHKcWRiYv5xXOQqvcl6/ba+6sbwquvu2crQBqnED6IySDhVWxwQwPxXoCtANKh2soTJl/Owran77Q1Hb0SgbpDjEXoQ3lA8yL2Yoyh3ZZdw165fAExekSpP0YmyXZKgakezmBNsrMTtOKwc9yrWgJDfzUN1JbUJ4YhXurGn2LDoswzJB/p9QSZZOENJzI1yJErphYVP1QbJ81aRk/s88mrZfOBIVmyAoczwPN71NJeyW0cV7nHgkNscNcnUQD/6f756fxFKzn9FLKtEAY7B8gqi5s7wNhW3kGljafNLulzA2eWMWPivh/lYwcMvEWdODpPqkpIq9P/0MxcNRghdji3nxVFluUQ=
  - secure: jMKjIcjqTvt3nCToM+gZltDzx+DLmhEPkfxwsPBB7b8Tm1nzssoVPZJ7KiQnNuxQosp7j63/aYnoCZXkUs50G38Kc8kNQOOuD4fPYHJLnuP6g//ouWg2jUH75Qch0ekg/NZrnO+dK6WCwhE27pYdaQnQmSRvZkUVYbvEVwhqTmsvM4Tpaleosdo+nXczQPUKIhXR7k8wnrnoTVRYC4wHabl+GKt80Go3MuU56m7L0cg3Cjn1/Pi4o5ojHqi4ursIuqf9Erc3nXOtLl9ITTusTp9rnw2y+KOcwJcU/j0oZnvzVG8qCaUX9c8bhpri+aRVH3teDiI6KohALkNZIDF/Uv7rqL5MUqo+Niiv6MlluUkrRHbBcNwUpb9irbZm7Ynr7yrtcFm0NPqczdpkedrEW+ekDeJ4pc0EMJu2UeiA4S2/ECiItQGHGf3k7V4t0EWUUU0dVit1CdVeFMmQTwKwAxW2MU+1uciuPVWVyqWXCKw0060lk70Xd60foLRXfVGyEDzZNrg0lyHTCMeWA++qXGXjxocmkenhk37qcbSEeNE8KuGYIk5tQW26Nr3Pttprt49mTe5rugD2DYRHYHaMAWBovIp5LiiBS9Ey08NU/miR+cIURfZE4ZEFF1NRXVBIZVWsbSOlQ7YGFOYfiIC0BCFyV728cmDk6C488v+W3+w=
