language: python
python:
- '3.7'
branches:
  only: master
install:
- pip install awscli
- pip install aws-sam-cli
script:
- sam validate
- sam build -b build/
- sam package --template-file build/template.yaml --s3-bucket $BUILD_ARTIFACT_BUCKET --output-template-file build/packaged.yaml
deploy:
  provider: script
  script: sam deploy --template-file build/packaged.yaml --stack-name website-api
  skip_cleanup: true
  on:
    branch: master
notifications:
  email:
    on_failure: always
env:
  global:
  - BUILD_ARTIFACT_BUCKET=kaustubhk-build-artifacts
  - AWS_DEFAULT_REGION=us-east-1
  - secure: A+pQf7d7B7gX4m1pYE8X4UjS3U6JSv99P7x/d5Yt5SiC4HHtyk3EI50cHfWULBLcmZtCY1UPRWSb5K7BxNRb77CUk+mACaYmIXFHtQjBJ1lmYjyeD4XyzwoGpQcq7PIgGHjB406i1ULz8DR9syOqXc5ZUzXFDKEQotWYl8UvAJocXWcqyiYuuo34k7iJvQHBa9Y9NrN6lx2K35d3yBY/9QrIWelbdjN3Fi0ZR0Zr20BD7Aijy3XYuUFQj8QLCg0VDxYL4SI1rw3hcA0H1CNrveC1KmNeL8veLpBx0w5RsII/1WPLnfQRrq84gFSb2UZZxYCbiYR76lEjja6iQlTuDElC4pDJ70n5N3cPT5am1K0YVibFfVzsWkTX86tKqzei4QWN0M/Qrj37IYre54j02H+qfZltzWrO8GxDMcPKKKtg/T4zyMTwQrP8T1nIOlvEdkX6nnDWx4vuHvZQ3Ove6iWUA4VuHaNkpjbsC5DNKf71Itsbvva/LpaZyKQXZWyP1E9reCgZ8iklJnViA0gw6U7PTfOQXY2S6s2nLHMwQedeKfEI1Y0y9Hm7jM3GFPc6gbcSu834eXlTRslHpG/6tyeeSm6NUj64GbIN+DA5atdOVtiH3MXMlkE9JCtlANHdWWzrzPb+EF8bartzdJ6du6c4swDdg3iCC1JH8ZfCbPo=
  - secure: V7j/Mwkwi0hoKjIz5Wuw+4BItL3SWUpcZ91Xzl93VaE59IQDxw+WhV/hnXkgi8vHWg3uHgi/jnxPr+OIBLPVJKDPOt9D1frJ99X2B+ap66DaGRaZml5cYD2rQGK7fe1L0Angrtzqbcw3o6ZOYntIACm/zWn7sLtObl3kFcw3BLkpCHOTR7b8XzkNaHHdfOHgZPh+h7TipMaU99QUGW7QDvzKr82aS0rPizePXKCbaYNRmhX8wHp72KfrbjKw7yp3dQIOavU1tPJdnXE7wta9/FF0oyMvkcO4rcDgPgyS1LPuXIGOmwdSN/iXU/nfNcRJCmEqUpZJCMd/F5p+W5NyKvVngB5Mn937nKXm9PMiTGV3A+3OWjvwOEJhUbESffx6Op5euBbj+C3hd8cJSPFcl2khlOY1o80nGLp9mngSoKQuTwL/whTDljwPZfulvGjxXaalzt+T6qbBCi53BVdcrhzBcvswjLMUYUB4u2GB+Nz1C8wtfLVW+f0/ljjTTS45aSeUmjzEkRxBdVzkIcpB+ptk5nryytlqGFbbkDiMbqqZHC+XRylyiJ23ER1CzkDLeRE8JczvJwD3EI66z4Z+EIHR1QrwWrp1Cd+EPlQbybjKfoie0hdUT9SY3rN0DAK6u2qd5nHamzMJ0+3NfqV8t3BUPh/6E6Qxi6EPe3P0StE=
