language: python
python:
- '3.7'
branches:
  only:
  - master
install:
- pip install awscli
- pip install aws-sam-cli
script:
- sam validate
- sam build -b build/
deploy:
  provider: script
  script: bash -e deploy.sh
  skip_cleanup: true
  on:
    branch: master
notifications:
  email:
    on_failure: always
env:
  global:
  - EMAIL_TEMPLATE_BUCKET=kaustubhk-email-templates
  - BUILD_ARTIFACT_BUCKET=kaustubhk-build-artifacts
  - AWS_DEFAULT_REGION=us-east-1
  - AWS_DEFAULT_OUTPUT=json
  - secure: "oX4s19JO9XmV3GcKWGdk8BTVNDQdifFXamU7wb5pp/tp7m0UIv7611Re0tVSQnAbemy8LL7M+O1Yr0gLfpiMPQmea0YMGCZIM63qOlrlObnSzFo79nTopCw2x90CM8JYAZzm2Gm41SXWKN0hoIPZ55py5BAWiLHbsxwM7uROppVXDp5AdrEyzsjB0oDfSD7/H+3hDYaNha2qiittciY/W476l/bi80qLUHtci9vH7J9cH3/ge2BP4w41jsDBJgk7K7/idqLzHPBZ/lfApAloooyKSJw0/J3mMmqZiO0KMZcaS6+gNUKPxyJ2is4hwPxxyS4l6BIhs+UOHIZXZajYbP6HplZ7hgzqnC17jKNGS1Sgyni+iL7jNQut+EJ2dr9FT+et0fwtLqu696EPOej3J43mKssw3fNL6vMMEEeJbRi16P/oOS9hPRQ50tAmnQV0LCqaZ/w31Xri6AD5vwLQE5qFlF7wWHxscBY1L5V+F953/5AxYGbmj97Dl71zD3JOvMcnRAJ7EmE9wVtEvPqVYkUQQaoEku1JhXggztc5x4DAbsY1NCkWqqnukI+y7g8YZlA/HHJ7X7feSjBMWgZDHUOpAJcPKsMdty5KsUOjFN+TTFe3o3/MGKxdFrZwJYKJgrkelDjI1enpvIFNMmn4XrvOMactiA3p9GvLxNOXLdA="
  - secure: "m68lZJxQn2a54/v6VaOVUnUVMJtyKxhI5MCE5wIxBriTC5PBfQfF7y4hgotb//ogmDCeu7SLVOcPlAbB2WmobacDvq5AqXvHlGcXaeVTVK477VYf4tZiTZAWy70QhvniXCNuan5ipoOd5ojEIeQmPa6eDhgL4F2672oN4S8txhqq7xSctkg/n5xN1ik4jJLmSVr2toy0+Tas9FpTc5Tc0PR3CWl7f9AT6LUKFgR/aJtAIoSb6ifvvKuDuBuNWtIORCzudhpUzKoULl2HMWqYKPku8R79Pu/Olnelxsb2S+2OUrHMl+DLfdDQYYz8ovaxLmWopfsWKvbhthL32Vn9BVSPdip++SVM0YRtsK+2gWTLcdjyyTpGsJRVCyWAnmGb4xCUuwJryvm8E4PHmvOh+UCHWp23BGSgyEwI1D81PnEjkBX+qkvKeA40lsIQgeNqrJylzhBFekvGuUtAl6v3xBHKAGhuLZSsV8bhma82GwBxDa2thugLlnfN2MZ2gGASp21CeelYBLDo7pxGX+MfL9AxgPkuvOLPt44V1kgis2ujGxoUpZVKBIjr7dzHXcgtvsCziX7xfIo2CypRzA9d2OKj8oopStL7/eVxnZsTUWXkeKUFNtTGEIQQMtzG+dItv5YLhQTNSF2ZGT4HUslmPGuZ2juNXkxMoqe/LXX4WlU="
