---
AWSTemplateFormatVersion: '2010-09-09'

Transform: 'AWS::Serverless-2016-10-31'

Description: 'SAM template for website API'

Parameters:
  ContactMeFormFunctionRoleARN:
    Type: 'String'
    AllowedPattern: 'arn:(aws[a-zA-Z-]*)?:iam::\d{12}:role/?[a-zA-Z_0-9+=,.@\-_/]+'
  BirthdayMailerFunctionRoleARN:
    Type: 'String'
    AllowedPattern: 'arn:(aws[a-zA-Z-]*)?:iam::\d{12}:role/?[a-zA-Z_0-9+=,.@\-_/]+'
  BirthdayPostFunctionRoleARN:
    Type: 'String'
    AllowedPattern: 'arn:(aws[a-zA-Z-]*)?:iam::\d{12}:role/?[a-zA-Z_0-9+=,.@\-_/]+'
  UnsubscribeFunctionRoleARN:
    Type: 'String'
    AllowedPattern: 'arn:(aws[a-zA-Z-]*)?:iam::\d{12}:role/?[a-zA-Z_0-9+=,.@\-_/]+'
  BirthdaysGetFunctionRoleARN:
    Type: 'String'
    AllowedPattern: 'arn:(aws[a-zA-Z-]*)?:iam::\d{12}:role/?[a-zA-Z_0-9+=,.@\-_/]+'
  EmailTemplateBucket:
    Type: 'String'
    MinLength: 3
    MaxLength: 63
  TextGenericTemplate:
    Type: 'String'
  HtmlGenericTemplate:
    Type: 'String'
  HtmlBirthdayTemplate:
    Type: 'String'
  SenderEmail:
    Type: 'String'
  BirthdaySenderEmail:
    Type: 'String'
  AdminEmail:
    Type: 'String'
Resources:
  RestApi:
    Type: 'AWS::Serverless::Api'
    Properties:
      Name: 'RestApi'
      MethodSettings:
        - HttpMethod: '*'
          ResourcePath: '/*'
          ThrottlingBurstLimit: 4
          ThrottlingRateLimit: 4.0
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: 'rest_api.yaml'
      StageName: 'beta'
      EndpointConfiguration: 'EDGE'
      OpenApiVersion: '3.0.1'
  BirthdayUserPool:
    Type: 'AWS::Cognito::UserPool'
    Properties:
      UserPoolName: 'BirthdayUserPool'
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: True
      MfaConfiguration: 'OFF'
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: True
          RequireNumbers: True
          RequireSymbols: True
          RequireUppercase: True
          TemporaryPasswordValidityDays: 1
  BirthdayUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref BirthdayUserPool
      ClientName: 'BirthdayUserPoolClient'
      GenerateSecret: False
      SupportedIdentityProviders:
        - 'COGNITO'
  ContactMeFormFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: 'ContactMeForm'
      CodeUri: 'ContactMeForm/'
      Handler: 'lambda_function.lambda_handler'
      Runtime: 'python3.7'
      Timeout: 15
      ReservedConcurrentExecutions: 4
      Role: !Ref ContactMeFormFunctionRoleARN
      Environment:
        Variables:
          BUCKET_NAME: !Ref EmailTemplateBucket
          TEXT_TEMPLATE: !Ref TextGenericTemplate
          HTML_TEMPLATE: !Ref HtmlGenericTemplate
          SENDER: !Ref SenderEmail
          ADMIN_EMAIL: !Ref AdminEmail
      Events:
        RestApiEvent:
          Type: 'Api'
          Properties:
            Path: '/contact-form'
            Method: 'post'
            RestApiId: !Ref RestApi
            Auth:
              Authorizer: 'CognitoAuth'
  BirthdayPostFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: 'BirthdayPost'
      CodeUri: 'BirthdayPost/'
      Handler: 'lambda_function.lambda_handler'
      Runtime: 'python3.7'
      Timeout: 15
      ReservedConcurrentExecutions: 2
      Role: !Ref BirthdayPostFunctionRoleARN
      Events:
        RestApiEvent:
          Type: 'Api'
          Properties:
            Path: '/birthday'
            Method: 'post'
            RestApiId: !Ref RestApi
  BirthdaysGetFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: 'BirthdaysGet'
      CodeUri: 'BirthdaysGet/'
      Handler: 'lambda_function.lambda_handler'
      Runtime: 'python3.7'
      Timeout: 15
      ReservedConcurrentExecutions: 2
      Role: !Ref BirthdaysGetFunctionRoleARN
  #      Events:
  #        RestApiEvent:
  #          Type: 'Api'
  #          Properties:
  #            Path: '/birthdays'
  #            Method: 'get'
  #            RestApiId: !Ref RestApi
  UnsubscribeFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: 'Unsubscribe'
      CodeUri: 'Unsubscribe/'
      Handler: 'lambda_function.lambda_handler'
      Runtime: 'python3.7'
      Timeout: 15
      ReservedConcurrentExecutions: 4
      Role: !Ref UnsubscribeFunctionRoleARN
      Events:
        RestApiEvent:
          Type: 'Api'
          Properties:
            Path: '/unsubscribe'
            Method: 'post'
            RestApiId: !Ref RestApi
  BirthdayMailerFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: 'BirthdayMailer'
      CodeUri: 'BirthdayMailer/'
      Handler: 'lambda_function.lambda_handler'
      Runtime: 'python3.7'
      Timeout: 15
      ReservedConcurrentExecutions: 2
      Role: !Ref BirthdayMailerFunctionRoleARN
      Environment:
        Variables:
          BUCKET_NAME: !Ref EmailTemplateBucket
          TEXT_TEMPLATE: !Ref TextGenericTemplate
          HTML_TEMPLATE: !Ref HtmlBirthdayTemplate
          SENDER: !Ref BirthdaySenderEmail
          ADMIN_EMAIL: !Ref AdminEmail
      Events:
        CronScheduler:
          Type: 'Schedule'
          Properties:
            Schedule: 'cron(0/15 * * * ? *)'
            Name: '15-minute-cron'
            Description: '15 minutes cron for birthday mailer'
            Enabled: True
  BirthdaysTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: 'DateKey'
          AttributeType: 'S'
        - AttributeName: 'TimeName'
          AttributeType: 'S'
        - AttributeName: 'UnsubscribeKey'
          AttributeType: 'S'
      BillingMode: 'PAY_PER_REQUEST'
      KeySchema:
        - AttributeName: 'DateKey'
          KeyType: 'HASH'
        - AttributeName: 'TimeName'
          KeyType: 'RANGE'
      GlobalSecondaryIndexes:
        - IndexName: 'UnsubscribeKeyIndex'
          KeySchema:
            - AttributeName: 'UnsubscribeKey'
              KeyType: 'HASH'
          Projection:
            ProjectionType: 'KEYS_ONLY'
      TableName: 'BirthdaysTable'

Outputs:
  RestApiEndpoint:
    Description: 'API Gateway endpoint URL for for Rest API'
    Value: !Sub 'https://${RestApi}.execute-api.${AWS::Region}.amazonaws.com/${RestApi.Stage}/'
  ContactMeFormARN:
    Description: 'ContactMeForm Function ARN'
    Value: !GetAtt ContactMeFormFunction.Arn
